version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      environment:
        - POSTGRES_DB=${DB_DATABASE}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

  go:
    container_name: go
    build:
      context: ./.docker/go
    depends_on:
      - "postgres"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: # create the volume for persisting data.